"""Bootstrap and repair a GeneratedTests xUnit project for a C# codebase."""

import os
import re
import subprocess
import sys

from csharp_parser import find_all_project_csproj_files, detect_target_framework

GENERATED_TESTS_DIR = "GeneratedTests"

# NuGet packages added to every generated test project
_NUGET_PACKAGES: list[tuple[str, str]] = [
    ("xunit", "2.9.3"),
    ("xunit.runner.visualstudio", "2.8.2"),
    ("Microsoft.NET.Test.Sdk", "17.13.0"),
    ("Moq", "4.20.72"),
    ("coverlet.collector", "6.0.4"),
]


def _run(args: list[str], cwd: str) -> None:
    """
    Run a CLI command; raise RuntimeError on non-zero exit or missing binary.
    Args:
        args (list[str]): The command and its arguments to execute.
        cwd (str): The working directory in which to execute the command.
    """

    env = os.environ.copy()
    env["DOTNET_NOLOGO"] = "1"
    env["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1"

    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            env=env,
        )
    except FileNotFoundError:
        raise RuntimeError(
            f"Command not found: {args[0]}\n"
            f"Python executable: {sys.executable}\n"
            f"PATH: {os.environ.get('PATH', '')}"
        )

    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed (exit {result.returncode}): {' '.join(args)}"
        )


# The placeholder reference written when no real .csproj was found at bootstrap time.
_FALLBACK_REF = "../YourProject.csproj"


def _csproj_content(target_framework: str, main_csproj_rels: list[str]) -> str:
    """
    Return the XML content for the generated test project's .csproj.
    Args:
        target_framework (str): The target framework to use, e.g. "net8.0".
        main_csproj_rels (list[str]): A list of relative paths to main .csproj files to reference.
    Returns:
        str: The XML content for the .csproj file.
    """

    packages_xml = "\n".join(
        f'    <PackageReference Include="{name}" Version="{version}" />'
        for name, version in _NUGET_PACKAGES
    )
    if main_csproj_rels:
        refs_xml = "\n".join(
            f'    <ProjectReference Include="{rel}" />'
            for rel in main_csproj_rels
        )
        project_refs_block = f"\n  <ItemGroup>\n{refs_xml}\n  </ItemGroup>\n"
    else:
        project_refs_block = ""

    return f"""\
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>{target_framework}</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
{packages_xml}
  </ItemGroup>
{project_refs_block}
</Project>
"""


def _placeholder_test_content() -> str:
    """Return a minimal placeholder test file."""

    return """\
// Bootstrap placeholder — replace with real tests generated by the agent.
using Xunit;

namespace GeneratedTests;

public class BootstrapTest
{
    [Fact]
    public void Bootstrap_AlwaysPasses()
    {
        Assert.True(true);
    }
}
"""


def repair_project_reference(test_project_dir: str, project_root: str) -> bool:
    """
    Inspect ``GeneratedTests.csproj`` for broken or placeholder
    ``<ProjectReference>`` entries and replace them with the real project
    references discovered from *project_root*.

    Returns ``True`` when the file was rewritten, ``False`` when no repair
    was needed or no real projects could be found.

    Args:
        test_project_dir (str): The directory of the GeneratedTests project.
        project_root (str): The root directory of the main C# project.
    Returns:
        bool: True if repairs were made, False otherwise.
    """

    csproj_path = os.path.join(test_project_dir, f"{GENERATED_TESTS_DIR}.csproj")
    if not os.path.exists(csproj_path):
        return False

    with open(csproj_path, encoding="utf-8") as f:
        content = f.read()

    # Detect placeholder reference
    has_fallback = _FALLBACK_REF.replace("\\", "/") in content.replace("\\", "/")

    # Detect any ProjectReference pointing to a file that no longer exists
    ref_paths = re.findall(r'<ProjectReference\s+Include="([^"]+)"', content)
    has_missing = any(
        not os.path.exists(
            os.path.normpath(os.path.join(test_project_dir, ref.replace("/", os.sep)))
        )
        for ref in ref_paths
    )

    if not has_fallback and not has_missing:
        return False  # nothing to repair

    main_csproj_files = find_all_project_csproj_files(project_root)
    if not main_csproj_files:
        return False  # cannot repair without a real project

    main_csproj_rels = [
        os.path.relpath(p, test_project_dir).replace("\\", "/")
        for p in main_csproj_files
    ]
    target_framework = detect_target_framework(project_root)
    new_content = _csproj_content(target_framework, main_csproj_rels)

    with open(csproj_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    return True


def bootstrap_csharp_test_project(project_root: str) -> str:
    """
    Ensure that a ``GeneratedTests/`` xUnit project exists inside *project_root*.

    If the project already exists its ``<ProjectReference>`` entries are
    validated; any broken or placeholder references are automatically repaired.
    Returns the absolute path to the GeneratedTests directory.

    Args:
        project_root (str): The root directory of the C# project to bootstrap tests for.
    """

    project_root = os.path.abspath(project_root)
    test_project_dir = os.path.join(project_root, GENERATED_TESTS_DIR)

    csproj_path = os.path.join(test_project_dir, f"{GENERATED_TESTS_DIR}.csproj")

    if os.path.exists(csproj_path):
        # Even if the project already exists, repair broken ProjectReferences.
        if repair_project_reference(test_project_dir, project_root):
            print(
                f"  Repaired broken ProjectReference(s) in "
                f"{os.path.relpath(csproj_path, project_root)}."
            )
            print("  Re-running dotnet restore after reference repair...")
            print(test_project_dir)
            _run(["dotnet", "restore", "--nologo"], cwd=test_project_dir)
        else:
            print(
                f"GeneratedTests project already exists at {test_project_dir} "
                "— skipping bootstrap."
            )
        return test_project_dir
    
    ##########################################################################
    #    Bootstrap a new GeneratedTests project from scratch, referencing    #
    #  all detected main .csproj files. This allows the agent to start with  #
    ##########################################################################

    os.makedirs(test_project_dir, exist_ok=True)

    target_framework = detect_target_framework(project_root)
    main_csproj_files = find_all_project_csproj_files(project_root)

    if main_csproj_files:
        main_csproj_rels = [
            os.path.relpath(p, test_project_dir).replace("\\", "/")
            for p in main_csproj_files
        ]
        names = ", ".join(os.path.basename(p) for p in main_csproj_files)
        print(f"  Found {len(main_csproj_files)} project reference(s): {names}")
    else:
        main_csproj_rels = []
        print(
            "  X  No .csproj found in or under the project root — "
            "the test project will have no ProjectReference. "
            "Add a <ProjectReference> to "
            f"{os.path.join(GENERATED_TESTS_DIR, GENERATED_TESTS_DIR + '.csproj')} "
            "manually if needed."
        )

    print(f"Bootstrapping GeneratedTests project (framework: {target_framework})...")

    # Write .csproj
    csproj_content = _csproj_content(
        target_framework=target_framework,
        main_csproj_rels=main_csproj_rels,
    )
    with open(csproj_path, "w", encoding="utf-8") as f:
        f.write(csproj_content)

    # Write placeholder test
    placeholder_path = os.path.join(test_project_dir, "BootstrapTest.cs")
    with open(placeholder_path, "w", encoding="utf-8") as f:
        f.write(_placeholder_test_content())

    # Restore NuGet packages
    print("  Restoring NuGet packages (dotnet restore)...")
    _run(["dotnet", "restore", "--nologo"], cwd=test_project_dir)

    # Verify the project builds
    print("  Verifying initial build (dotnet build)...")
    _run(["dotnet", "build", "--nologo", "-v", "minimal"], cwd=test_project_dir)

    print(f"  ✓  GeneratedTests project ready at {test_project_dir}")
    return test_project_dir
